### ISSUE TITLE
GET request could not send body

### ISSUE THREAD

**Issue by Tex-Tang** [chinese-bbb/web-backend#3]
#### Description
I have found an error in `GET /complaintByUser` api request. After doing some searching, I found the error happens because of GET request could not send body. You can refer to [this](https://github.com/flask-restful/flask-restful/issues/510).

#### Steps to reproduce
1. Send `GET` request to endpoint `/complaintByUser` or 'complaintByMerchant`
2. You would get an error with message which says complaint id Missing required parameter in the JSON body.

Other than that, I had tried another possible solution to fix it.
1. Send `GET` request to endpoint `/complaintByUser` or 'complaintByMerchant` with header `{content-type: "application/json"}` and request body that written in api documentation.
2. You would get another error with message which says complaint id Missing required parameter in the JSON body

#### Expected result
The response should be same as the result shown in api documentation.

#### Screenshots
![image](https://user-images.githubusercontent.com/14901260/59287466-4c0daa80-8ca4-11e9-95c9-6c5a7cde8962.png)

![image](https://user-images.githubusercontent.com/14901260/59287294-f33e1200-8ca3-11e9-9bed-c4b566ba9bb2.png)

**Comment by kunkun-tang** [comment]
Thanks a lot for reporting the issue. It has been fixed in https://github.com/chinese-bbb/web-backend/commit/0acc14d57ae2cac5829cb71a9d336b538ad3c850
